import { getOpenCodePlusplusPackageVersion, OPENCODE_PLUSPLUS_PACKAGE_NAME } from "../../core/package-info.js";

export const OPENCODE_SIDECAR_PLUGIN_PATH = ".opencode/plugins/opencode-plusplus.ts";

export interface OpenCodeSidecarPluginTemplateOptions {
  version?: string;
  generatedAt?: string;
}

export function opencodeSidecarPluginTemplate(runtimeImport = opencodeSidecarRuntimeImport(), options: OpenCodeSidecarPluginTemplateOptions = {}): string {
  const version = options.version ?? getOpenCodePlusplusPackageVersion();
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  return `/**
 * OpenCode++ OpenCode Sidecar Plugin
 *
 * Generated by: ${OPENCODE_PLUSPLUS_PACKAGE_NAME}
 * Package version: ${version}
 * Generated at: ${generatedAt}
 *
 * Edit only when you want to customize how OpenCode
 * presents the OpenCode++ harness inside this repository.
 */

import { createOpenCodePlusPlusSidecar } from ${JSON.stringify(runtimeImport)};

export const OPENCODE_PLUSPLUS_PLUGIN_VERSION = ${JSON.stringify(version)};
export const OPENCODE_PLUSPLUS_GENERATED_AT = ${JSON.stringify(generatedAt)};
export const OpenCodePlusPlusSidecar = createOpenCodePlusPlusSidecar;
export default OpenCodePlusPlusSidecar;
`;
}

export function opencodeSidecarRuntimeImport(): string {
  const extension = import.meta.url.endsWith(".ts") ? "ts" : "js";
  return new URL(`./plugin-runtime/index.${extension}`, import.meta.url).href;
}
