export const OPENCODE_SIDECAR_PLUGIN_PATH = ".opencode/plugins/opencode-plusplus.ts";

export function opencodeSidecarPluginTemplate(runtimeImport = opencodeSidecarRuntimeImport()): string {
  return `/**
 * OpenCode++ OpenCode Sidecar Plugin
 *
 * Generated by \`opencode-plusplus\`. Edit only when you want to customize how OpenCode
 * presents the OpenCode++ harness inside this repository.
 */

import { createOpenCodePlusPlusSidecar } from ${JSON.stringify(runtimeImport)};

export const OpenCodePlusPlusSidecar = createOpenCodePlusPlusSidecar;
export default OpenCodePlusPlusSidecar;
`;
}

export function opencodeSidecarRuntimeImport(): string {
  const extension = import.meta.url.endsWith(".ts") ? "ts" : "js";
  return new URL(`./plugin-runtime/index.${extension}`, import.meta.url).href;
}
