export const OPENCODE_SIDECAR_PLUGIN_PATH = ".opencode/plugins/code-agent-plusplus.ts";

export function opencodeSidecarPluginTemplate(): string {
  return String.raw`/**
 * Code Agent++ OpenCode Sidecar Plugin
 *
 * Generated by \`capp\`. Edit only when you want to customize how OpenCode
 * presents the Code Agent++ harness inside this repository.
 */

import { appendFileSync, mkdirSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";

export const CodeAgentPlusPlusSidecar = async ({ directory, worktree }) => {
  const eventLog = path.join(directory, ".agent-context", "traces", "opencode-sidecar-events.jsonl");

  function record(type, payload = {}) {
    try {
      mkdirSync(path.dirname(eventLog), { recursive: true });
      appendFileSync(
        eventLog,
        JSON.stringify({
          type,
          ts: new Date().toISOString(),
          directory,
          worktree,
          ...payload
        }) + "\n",
        "utf8"
      );
    } catch {
      // The sidecar must never break OpenCode. Verification can still run manually.
    }
  }

  return {
    name: "code-agent-plusplus-sidecar",
    event: async ({ event }) => {
      const type = event?.type;
      if (event?.type === "session.created") {
        record("session.created");
        console.log([
          "Code Agent++ sidecar active.",
          "Project: " + directory,
          "Worktree: " + worktree,
          "Use /capp <task> for harness-led execution.",
          "Use /capp-verify before finalizing a task.",
          "Use capp oc report --last for the latest gate report."
        ].join("\n"));
      }

      if (type === "file.edited") {
        const file = event?.properties?.file ?? event?.properties?.path ?? event?.file ?? event?.path ?? "unknown";
        record("file.edited", { file });
        console.log("Code Agent++ sidecar noticed an edit: " + file + ". Run capp sidecar verify before finalizing.");
      }

      if (type === "session.idle") {
        record("session.idle");
        const verify = spawnSync("capp", ["sidecar", "verify", directory, "--quiet"], {
          cwd: directory,
          encoding: "utf8",
          shell: process.platform === "win32"
        });
        record("sidecar.verify", { exitCode: verify.status ?? 1 });
        if ((verify.status ?? 1) !== 0) {
          const output = (verify.stdout || verify.stderr || "Code Agent++ sidecar found blockers. Run capp sidecar verify .").trim();
          console.log(output);
        }
      }
    }
  };
};
`;
}
