export const OPENCODE_SIDECAR_PLUGIN_PATH = ".opencode/plugins/code-agent-plusplus.ts";

export function opencodeSidecarPluginTemplate(): string {
  return String.raw`/**
 * Code Agent++ OpenCode Sidecar Plugin
 *
 * Generated by \`capp\`. Edit only when you want to customize how OpenCode
 * presents the Code Agent++ harness inside this repository.
 */

export const CodeAgentPlusPlusSidecar = async ({ directory, worktree }) => {
  return {
    name: "code-agent-plusplus-sidecar",
    event: async ({ event }) => {
      if (event?.type === "session.created") {
        console.log([
          "Code Agent++ sidecar active.",
          "Project: " + directory,
          "Worktree: " + worktree,
          "Use /capp <task> for harness-led execution.",
          "Use /capp-verify before finalizing a task.",
          "Use capp oc report --last for the latest gate report."
        ].join("\n"));
      }
    }
  };
};
`;
}
