export const OPENCODE_SIDECAR_PLUGIN_PATH = ".opencode/plugins/code-agent-plusplus.ts";

export function opencodeSidecarPluginTemplate(): string {
  return String.raw`/**
 * Code Agent++ OpenCode Sidecar Plugin
 *
 * Generated by \`capp\`. Edit only when you want to customize how OpenCode
 * presents the Code Agent++ harness inside this repository.
 */

import { appendFileSync, mkdirSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";

export const CodeAgentPlusPlusSidecar = async ({ directory, worktree, client }) => {
  const eventLog = path.join(directory, ".agent-context", "traces", "opencode-sidecar-events.jsonl");

  function record(type, payload = {}) {
    try {
      mkdirSync(path.dirname(eventLog), { recursive: true });
      appendFileSync(
        eventLog,
        JSON.stringify({
          type,
          ts: new Date().toISOString(),
          directory,
          worktree,
          ...payload
        }) + "\n",
        "utf8"
      );
    } catch {
      // The sidecar must never break OpenCode. Verification can still run manually.
    }
  }

  function log(level, message, extra = {}) {
    record("sidecar.log", { level, message, ...extra });
    try {
      client?.app?.log?.({
        service: "code-agent-plusplus",
        level,
        message,
        extra
      });
    } catch {
      // Structured logging is best-effort and must never interrupt OpenCode.
    }
  }

  function commandFromTool(tool, args) {
    if (!args || typeof args !== "object") return null;
    if (typeof args.command === "string") return args.command;
    if (typeof args.cmd === "string") return args.cmd;
    if (typeof args.shell === "string") return args.shell;
    if (typeof args.input === "string" && /^(bash|shell|terminal|run)$/i.test(String(tool ?? ""))) return args.input;
    return null;
  }

  function pathsFromTool(args) {
    if (!args || typeof args !== "object") return [];
    const values = [];
    for (const key of ["path", "file", "filepath", "filePath", "target", "destination"]) {
      if (typeof args[key] === "string") values.push(args[key]);
    }
    if (Array.isArray(args.files)) {
      for (const file of args.files) if (typeof file === "string") values.push(file);
    }
    return values;
  }

  function runCommandGuard(tool, args) {
    const command = commandFromTool(tool, args);
    const paths = pathsFromTool(args);
    if (!command && paths.length === 0) return;

    const cliArgs = ["sidecar", "check-command", directory, "--json"];
    if (command) cliArgs.push("--command", command);
    else cliArgs.push("--command", "path-check");
    for (const file of paths) cliArgs.push("--path", file);

    const check = spawnSync("capp", cliArgs, {
      cwd: directory,
      encoding: "utf8",
      shell: process.platform === "win32"
    });
    record("sidecar.check-command", { tool, command, paths, exitCode: check.status ?? 1 });
    if ((check.status ?? 1) !== 0) {
      const output = (check.stdout || check.stderr || "Code Agent++ blocked a command or protected path.").trim();
      log("error", "blocked tool execution", { tool, command, paths });
      throw new Error(output);
    }
    log("debug", "tool execution allowed", { tool, command, paths });
  }

  return {
    name: "code-agent-plusplus-sidecar",
    "tool.execute.before": async ({ tool, args }) => {
      runCommandGuard(tool, args);
    },
    event: async ({ event }) => {
      const type = event?.type;
      if (event?.type === "session.created") {
        record("session.created");
        log("debug", "sidecar active", { directory, worktree });
      }

      if (type === "file.edited") {
        const file = event?.properties?.file ?? event?.properties?.path ?? event?.file ?? event?.path ?? "unknown";
        record("file.edited", { file });
        log("debug", "file edited", { file });
      }

      if (type === "session.idle") {
        record("session.idle");
        const verify = spawnSync("capp", ["sidecar", "verify", directory, "--quiet"], {
          cwd: directory,
          encoding: "utf8",
          shell: process.platform === "win32"
        });
        record("sidecar.verify", { exitCode: verify.status ?? 1 });
        if ((verify.status ?? 1) !== 0) {
          const output = (verify.stdout || verify.stderr || "Code Agent++ sidecar found blockers. Run capp sidecar verify .").trim();
          log("error", "sidecar verification blocked", { exitCode: verify.status ?? 1 });
          console.log(output);
        } else {
          log("debug", "sidecar verification passed");
        }
      }
    }
  };
};
`;
}
