import { estimateTokens } from "../core/token-estimator.js";
import type { AgentsSection, ContextPackage, IndexedFile } from "../core/types.js";
import { bullet, code, heading } from "./markdown.js";

export function renderAgentsMd(context: ContextPackage): string {
  const mode = context.config.agents.mode;
  const sections = mode === "minimal" ? renderMinimalAgentsMd(context) : renderExpandedAgentsMd(context, mode === "full");

  return enforceAgentsBudget(sections, context.config.agents.maxTokens);
}

function renderMinimalAgentsMd(context: ContextPackage): string[] {
  const include = new Set<AgentsSection>(context.config.agents.include);
  const sections = [
    "<!-- generated-by: repo-to-agent-context -->",
    "<!-- generated-file: .agent-context/AGENTS.generated.md -->",
    "",
    heading(1, "Generated Agent Guide"),
    "",
    "L0 operating rules. Keep this file loaded by default; load deeper context only when the task requires it."
  ];

  if (include.has("safety")) {
    sections.push(
      "",
      heading(2, "Must-Read Rules"),
      bullet([
        "Inspect relevant source files before behavior-changing edits; generated summaries are not a source-of-truth replacement.",
        ...requiredCheckRules(context),
        "Do not commit secrets, local config, dependency folders, or generated build output such as `repo-context.local.yml`, API keys, `node_modules/`, `dist/`, or coverage artifacts.",
        "Preserve existing project conventions and command patterns unless the source code clearly requires a change."
      ]),
      "",
      heading(2, "Default Workflow"),
      bullet(defaultWorkflow())
    );
  }

  if (include.has("entrypoints")) {
    sections.push("", heading(2, "Project Entrypoints"), bullet(projectEntrypoints(context)));
  }

  if (include.has("commands")) {
    sections.push("", heading(2, "Commands"), bullet(commandLines(context)));
  }

  if (include.has("contextLinks")) {
    sections.push(
      "",
      heading(2, "Context Layers"),
      bullet(contextLinks(context)),
      "",
      heading(2, "Harness Runtime Files"),
      bullet(harnessRuntimeLinks()),
      "",
      heading(2, "Before Closing"),
      bullet(beforeClosingCommands())
    );
  }

  return sections;
}

function renderExpandedAgentsMd(context: ContextPackage, full: boolean): string[] {
  const keyFileLimit = full ? 20 : 10;
  const moduleLimit = full ? 12 : 6;
  const keyFiles = context.keyFiles.slice(0, keyFileLimit).map(formatKeyFile);
  const modules = [...context.index.modules]
    .sort((a, b) => b.importanceScore - a.importanceScore)
    .slice(0, moduleLimit)
    .map((module) => `${code(module.name)} - ${module.summary}`);

  return [
    "<!-- generated-by: repo-to-agent-context -->",
    "<!-- generated-file: .agent-context/AGENTS.generated.md -->",
    "",
    heading(1, "Generated Agent Guide"),
    "",
    "This file was generated by Repo-to-Agent-Context. Keep root instructions concise; use the layer map before opening deeper `.agent-context/` materials.",
    "",
    heading(2, "Must-Read Rules"),
    bullet([
      "Inspect source files before making behavior-changing edits.",
      ...requiredCheckRules(context),
      "Do not treat generated summaries as a replacement for source code.",
      "Avoid committing secrets, local config, dependency folders, or generated build output."
    ]),
    "",
    heading(2, "Default Workflow"),
    bullet(defaultWorkflow()),
    "",
    heading(2, "Project Overview"),
    bullet([
      `Languages: ${context.scan.languages.join(", ") || "none detected"}`,
      `Frameworks: ${context.scan.frameworks.join(", ") || "none detected"}`,
      `Package managers: ${context.scan.packageManagers.join(", ") || "none detected"}`,
      `Entrypoints: ${context.scan.entrypoints.map(code).join(", ") || "none detected"}`,
      `Agent readiness: ${context.readiness.grade} / ${context.readiness.score}`
    ]),
    "",
    heading(2, "Commands"),
    bullet(commandLines(context)),
    "",
    heading(2, "L3 Important Files"),
    "Load these only after the task boundary is clear.",
    "",
    bullet(keyFiles),
    "",
    heading(2, "Module Map"),
    bullet(modules),
    "",
    heading(2, "Context Layers"),
    bullet(contextLinks(context)),
    "",
    heading(2, "Harness Runtime Files"),
    bullet(harnessRuntimeLinks()),
    "",
    heading(2, "Before Closing"),
    bullet(beforeClosingCommands())
  ];
}

function defaultWorkflow(): string[] {
  return [
    "Read `AGENTS.md` only before the task is concrete.",
    'For a concrete task, run `repo-context run "<task>" .` or inspect `.agent-context/runs/<task-id>/` when a task run exists.',
    "Do not load the full `.agent-context/` directory unless L1/L2 context is insufficient.",
    "Prefer source files over generated summaries for behavior, API, and test decisions."
  ];
}

function requiredCheckRules(context: ContextPackage): string[] {
  const checks = unique([...context.scan.typecheckCommands, ...context.scan.lintCommands, ...context.scan.testCommands]);

  if (checks.length === 0) {
    return ["No test/check command was detected; document what validation you performed before finishing."];
  }

  return [`Before finishing, run the relevant detected checks: ${checks.map(code).join(", ")}.`];
}

function commandLines(context: ContextPackage): string[] {
  const commands = [
    ...context.scan.runCommands.map((item) => `Run: ${code(item)}`),
    ...context.scan.typecheckCommands.map((item) => `Typecheck: ${code(item)}`),
    ...context.scan.lintCommands.map((item) => `Lint: ${code(item)}`),
    ...context.scan.testCommands.map((item) => `Test: ${code(item)}`)
  ];

  return unique(commands).length > 0 ? unique(commands) : ["No run, lint, typecheck, or test command detected."];
}

function projectEntrypoints(context: ContextPackage): string[] {
  const entries = context.scan.entrypoints.map((entry) => `Entrypoint: ${code(entry)}`);
  const anchors = selectAnchorFiles(context).map((file) => `Anchor: ${formatKeyFile(file)}`);

  return [...entries, ...anchors].length > 0
    ? [...entries, ...anchors]
    : ["No entrypoint detected; start with `.agent-context/repo-summary.md` and inspect source files directly."];
}

function contextLinks(context: ContextPackage): string[] {
  const links = [
    `${code("L0 AGENTS.md")} - always-loaded operating rules only`,
    `${code("L1 .agent-context/repo-summary.md")} - compact repository overview for task start`,
    `${code("L1 .agent-context/onboarding.md")} - first-read workflow and commands`,
    `${code("L1 .agent-context/context-layers.md")} - layer map for all generated outputs`,
    `${code("L2 .agent-context/runs/")} - complete task runs generated for concrete work`,
    `${code("L2 .agent-context/tasks/")} - standalone task packs generated or prebuilt for concrete work`,
    `${code("L3 .agent-context/key-files.md")} - ranked evidence index; load only when needed`,
    `${code("L3 .agent-context/index/")} - symbols, files, modules, and chunks for targeted lookup`,
    `${code("L3 .agent-context/evidence/")} - analyzer evidence for deeper inspection`
  ];

  if (context.config.outputs.modules) {
    links.push(`${code("L3 .agent-context/module-map.md")} - module responsibilities after task scope is known`);
    links.push(`${code("L3 .agent-context/architecture.md")} - architecture notes and evidence`);
  }
  if (context.config.outputs.graph) {
    links.push(`${code("L3 .agent-context/dependency-graph.md")} - file and module dependency graph`);
    links.push(`${code("L3 .agent-context/graphs/")} - Mermaid and JSON graph artifacts`);
  }
  if (context.config.outputs.readiness) {
    links.push(`${code("L3 .agent-context/readiness.md")} - agent-readiness gaps and evidence`);
  }
  if (context.config.outputs.rag) {
    links.push(`${code("L3 .agent-context/rag/")} - RAG-ready export documents`);
  }

  return links;
}

function harnessRuntimeLinks(): string[] {
  return [
    `${code(".agent-context/contracts/")} - machine-checkable edit, command, test, and safety boundaries`,
    `${code(".agent-context/runs/")} - complete task run contexts with plan, pack, tests, impact, verify, and prompts`,
    `${code(".agent-context/loops/")} - loop controller decisions when written with ${code('repo-context loop "<task>" . --write')}`,
    `${code(".agent-context/traces/")} - execution trace records for agent edits, tests, verification, and final state`,
    `${code(".agent-context/delta/")} - context delta and files the agent should re-read after repository changes`
  ];
}

function beforeClosingCommands(): string[] {
  return [
    `Prefer ${code("repo-context policy . --base main --trace <trace-id>")} when a trace exists.`,
    `Run ${code("repo-context verify --diff .")} and ${code('repo-context loop "<task>" . --phase after-edit')} before final review.`,
    `Check ${code("repo-context freshness .")} and ${code("repo-context drift .")} if generated context may be stale.`
  ];
}

function formatKeyFile(file: IndexedFile): string {
  return `${code(file.path)} - ${file.importanceReasons.slice(0, 2).join(", ") || file.kind}`;
}

function selectAnchorFiles(context: ContextPackage): IndexedFile[] {
  return context.keyFiles
    .filter((file) => !context.scan.entrypoints.includes(file.path))
    .filter((file) => !isLowValueAnchor(file))
    .slice(0, 3);
}

function isLowValueAnchor(file: IndexedFile): boolean {
  if (file.kind !== "config") {
    return false;
  }

  return !/(^|\/)(package\.json|pyproject\.toml|Cargo\.toml|go\.mod|Dockerfile|docker-compose\.yml|docker-compose\.yaml)$/i.test(file.path);
}

function enforceAgentsBudget(sections: string[], maxTokens: number): string {
  const kept: string[] = [];
  for (const section of sections) {
    const candidate = [...kept, section].join("\n");
    if (estimateTokens(candidate) > maxTokens && kept.length > 0) {
      kept.push("", `_Truncated to stay within agents.maxTokens (${maxTokens}). Read layer-specific files under \`.agent-context/\` only as needed._`);
      break;
    }
    kept.push(section);
  }

  const rendered = kept.join("\n");
  if (estimateTokens(rendered) <= maxTokens) {
    return rendered;
  }

  return `${rendered.slice(0, Math.max(0, maxTokens * 4 - 180)).trim()}\n\n_Truncated to stay within agents.maxTokens (${maxTokens})._`;
}

function unique<T>(items: T[]): T[] {
  return [...new Set(items)];
}
