import type { ContextPackage } from "../core/types.js";
import { bullet, code, heading } from "./markdown.js";

export function renderAgentsMd(context: ContextPackage): string {
  const keyFiles = context.keyFiles.slice(0, 12).map((file) => `${code(file.path)} - ${file.importanceReasons.slice(0, 3).join(", ") || file.kind}`);
  const generatedContext = [
    code(".agent-context/repo-summary.md"),
    code(".agent-context/key-files.md"),
    code(".agent-context/onboarding.md"),
    code(".agent-context/token-savings.md")
  ];
  if (context.config.outputs.modules) {
    generatedContext.push(code(".agent-context/module-map.md"), code(".agent-context/architecture.md"));
  }
  if (context.config.outputs.graph) {
    generatedContext.push(code(".agent-context/dependency-graph.md"));
  }
  if (context.config.outputs.readiness) {
    generatedContext.push(code(".agent-context/readiness.md"));
  }
  if (context.config.outputs.tasks) {
    generatedContext.push(code(".agent-context/tasks/"));
  }
  if (context.config.outputs.rag) {
    generatedContext.push(code(".agent-context/rag/"));
  }
  const modules = [...context.index.modules]
    .sort((a, b) => b.importanceScore - a.importanceScore)
    .slice(0, 8)
    .map((module) => `${code(module.name)} - ${module.summary}`);

  return [
    "<!-- generated-by: repo-to-agent-context -->",
    "",
    heading(1, "Agent Guide"),
    "",
    "This file was generated by Repo-to-Agent-Context. It gives coding agents a compact starting map for this repository.",
    "",
    heading(2, "Project Overview"),
    bullet([
      `Languages: ${context.scan.languages.join(", ") || "none detected"}`,
      `Frameworks: ${context.scan.frameworks.join(", ") || "none detected"}`,
      `Package managers: ${context.scan.packageManagers.join(", ") || "none detected"}`,
      `Entrypoints: ${context.scan.entrypoints.map(code).join(", ") || "none detected"}`,
      `Agent readiness: ${context.readiness.score}/100`
    ]),
    "",
    heading(2, "How To Run"),
    bullet(context.scan.runCommands.map(code)),
    "",
    heading(2, "How To Test"),
    bullet(context.scan.testCommands.map(code)),
    "",
    heading(2, "Important Files"),
    bullet(keyFiles),
    "",
    heading(2, "Module Map"),
    bullet(modules),
    "",
    heading(2, "Generated Context"),
    bullet(generatedContext),
    "",
    heading(2, "Safety Rules For Agents"),
    bullet([
      "Inspect source files before making behavior-changing edits.",
      "Do not treat generated summaries as a replacement for source code.",
      "Preserve project conventions and existing command patterns.",
      "Avoid committing secrets or generated dependency folders into context files."
    ])
  ].join("\n");
}
