import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { ContextPackage } from "../core/types.js";
import { renderAgentsMd } from "./agents-md.js";
import { renderArchitecture } from "./architecture.js";
import { renderDependencyGraph, renderMermaidGraph } from "./dependency-graph.js";
import { renderKeyFiles } from "./key-files.js";
import { renderModuleMap } from "./module-map.js";
import { renderOnboarding } from "./onboarding.js";
import { renderRepoSummary } from "./repo-summary.js";

export interface WriteResult {
  files: string[];
}

export function writeContextPackage(context: ContextPackage): WriteResult {
  const root = context.scan.root;
  const contextDir = path.join(root, ".agent-context");
  const indexDir = path.join(contextDir, "index");
  const graphDir = path.join(contextDir, "graphs");
  const written: string[] = [];

  mkdirSync(indexDir, { recursive: true });
  mkdirSync(graphDir, { recursive: true });

  write(root, resolveAgentsFileName(root), renderAgentsMd(context), written);
  write(contextDir, "repo-summary.md", renderRepoSummary(context), written);
  write(contextDir, "key-files.md", renderKeyFiles(context), written);
  write(contextDir, "module-map.md", renderModuleMap(context), written);
  write(contextDir, "dependency-graph.md", renderDependencyGraph(context), written);
  write(contextDir, "architecture.md", renderArchitecture(context), written);
  write(contextDir, "onboarding.md", renderOnboarding(context), written);
  write(graphDir, "dependencies.mmd", renderMermaidGraph(context), written);
  writeJson(graphDir, "dependencies.json", context.graph, written);
  writeJson(indexDir, "files.json", context.index.files, written);
  writeJson(indexDir, "symbols.json", context.index.symbols, written);
  writeJson(indexDir, "modules.json", context.index.modules, written);
  writeJson(indexDir, "chunks.json", buildChunks(context), written);

  return { files: written };
}

function resolveAgentsFileName(root: string): string {
  const agentsPath = path.join(root, "AGENTS.md");
  if (!existsSync(agentsPath)) {
    return "AGENTS.md";
  }

  const existing = readFileSync(agentsPath, "utf8");
  if (
    existing.includes("generated-by: repo-to-agent-context")
    || existing.includes("This file was generated by Repo-to-Agent-Context")
  ) {
    return "AGENTS.md";
  }

  return "AGENTS.generated.md";
}

function write(baseDir: string, fileName: string, content: string, written: string[]): void {
  const filePath = path.join(baseDir, fileName);
  writeFileSync(filePath, `${content.trim()}\n`, "utf8");
  written.push(filePath);
}

function writeJson(baseDir: string, fileName: string, value: unknown, written: string[]): void {
  write(baseDir, fileName, JSON.stringify(value, null, 2), written);
}

function buildChunks(context: ContextPackage): Array<{
  path: string;
  moduleName: string;
  tokenEstimate: number;
  summary: string;
}> {
  return context.index.files.map((file) => ({
    path: file.path,
    moduleName: file.moduleName,
    tokenEstimate: file.tokenEstimate,
    summary: file.summary
  }));
}
